package com.fujitsu.cloudlab.cart.api;

import com.fujitsu.cloudlab.cart.model.Cart;
import com.fujitsu.cloudlab.cart.model.CartSearchCriteria;
import com.fujitsu.cloudlab.cart.service.CartWriterService;
import com.fujitsu.cloudlab.commons.constants.AppConstants;
import com.fujitsu.cloudlab.commons.exception.ApiException;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiParam;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/cartWriter")
@Api(tags = {"Cart"})
public class CartWriterController {

  @Autowired CartWriterService cartWriterService;

  @PostMapping(
      consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
      produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
  public Cart actionCart(
      @ApiParam(
              value = "A unique id for each request generated by each application",
              required = true)
          @RequestHeader(value = AppConstants.TRANSACTION_ID, required = true)
          String transactionId,
      @RequestBody CartSearchCriteria searchCriteria)
      throws ApiException {
    return cartWriterService.createCart(searchCriteria, transactionId);
  }
}
